      MODULE CONFIG
          IMPLICIT NONE
          CHARACTER(LEN = 2), PARAMETER :: MAGICNUMBER = "P3"
          INTEGER, PARAMETER :: DIMC=500, DIMR=500, DIMD=1, MAXCOLOR=255
      END MODULE CONFIG

