      PROGRAM MAIN
          USE CONFIG
          USE DISPLAY

          IMPLICIT NONE
          INTEGER, DIMENSION(3, DIMD, DIMC, DIMR) :: THEDISPLAY

          CALL DISPLAY_PRINT(THEDISPLAY)
      END PROGRAM MAIN

